name: Generate Languages SVG
on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate languages
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_LANGUAGE: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIME: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "True"
          SYMBOL_VERSION: 3
          COMMIT_MESSAGE: "Atualização automática das linguagens"
